version: '3.3'

services:

  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  main:
    build: .
    entrypoint: script/main.sh
    depends_on:
      - rabbitmq
    stdin_open: true
    tty: true
